/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Andy
 */
public class ViewCompras extends javax.swing.JFrame {

    /**
     * Creates new form ViewCompras
     */
    public ViewCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel_compra = new javax.swing.JPanel();
        jl_fechacompra = new javax.swing.JLabel();
        jl_nombresucursal = new javax.swing.JLabel();
        jl_nombreadmin = new javax.swing.JLabel();
        jl_nombreproveedor = new javax.swing.JLabel();
        jtf_idcompra = new javax.swing.JTextField();
        jcb_dia = new javax.swing.JComboBox<>();
        jcb_mes = new javax.swing.JComboBox<>();
        jtf_anio = new javax.swing.JTextField();
        jcb_nombresucursal = new javax.swing.JComboBox<>();
        jcb_nombreadmin = new javax.swing.JComboBox<>();
        jcb_nombreproveedor = new javax.swing.JComboBox<>();
        jl_subtotal = new javax.swing.JLabel();
        jl_iva = new javax.swing.JLabel();
        jl_totalcompra = new javax.swing.JLabel();
        jtf_totalcompra = new javax.swing.JTextField();
        jtf_iva = new javax.swing.JTextField();
        jtf_subtotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jb_nuevo = new javax.swing.JButton();
        jb_insertar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jl_idcompra = new javax.swing.JLabel();
        jPanel_detallecompra = new javax.swing.JPanel();
        jl_nombreproducto = new javax.swing.JLabel();
        jl_precio = new javax.swing.JLabel();
        jl_cantidad = new javax.swing.JLabel();
        jcb_nombreproducto = new javax.swing.JComboBox<>();
        jtf_idcompra_det = new javax.swing.JTextField();
        jtf_precio = new javax.swing.JTextField();
        jtf_cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_detalle_compra = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jb_agregarproducto = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jl_idcompra_det = new javax.swing.JLabel();
        jb_fincompra = new javax.swing.JButton();
        jb_eliminarproducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Compras");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ferreteria ACME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_compra.setBackground(new java.awt.Color(153, 153, 153));

        jl_fechacompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_fechacompra.setText("Fecha de compra:");

        jl_nombresucursal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombresucursal.setText("Nombre Sucursal:");

        jl_nombreadmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombreadmin.setText("Nombre del Administrador:");

        jl_nombreproveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombreproveedor.setText("Nombre del Proveedor:");

        jtf_idcompra.setEnabled(false);

        jcb_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jcb_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jcb_nombreproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_nombreproveedorActionPerformed(evt);
            }
        });

        jl_subtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_subtotal.setText("Subtotal:");

        jl_iva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_iva.setText("I.V.A:");

        jl_totalcompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_totalcompra.setText("Total de Compra:");

        jtf_totalcompra.setEditable(false);
        jtf_totalcompra.setText("0.0");

        jtf_iva.setEditable(false);
        jtf_iva.setText("0.0");

        jtf_subtotal.setEditable(false);
        jtf_subtotal.setText("0.0");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("$");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("$");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("$");

        jb_nuevo.setBackground(new java.awt.Color(153, 153, 153));
        jb_nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_nuevo.setText("Nuevo");
        jb_nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jb_insertar.setBackground(new java.awt.Color(153, 153, 153));
        jb_insertar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_insertar.setText("Insertar");
        jb_insertar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));

        jb_modificar.setBackground(new java.awt.Color(153, 153, 153));
        jb_modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_modificar.setText("Modificar");
        jb_modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));

        jl_idcompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_idcompra.setText("ID de Compra:");

        javax.swing.GroupLayout jPanel_compraLayout = new javax.swing.GroupLayout(jPanel_compra);
        jPanel_compra.setLayout(jPanel_compraLayout);
        jPanel_compraLayout.setHorizontalGroup(
            jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_compraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_fechacompra)
                    .addComponent(jl_nombresucursal)
                    .addComponent(jl_nombreadmin)
                    .addComponent(jl_nombreproveedor)
                    .addComponent(jl_idcompra))
                .addGap(33, 33, 33)
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_compraLayout.createSequentialGroup()
                        .addComponent(jcb_dia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtf_idcompra)
                    .addComponent(jcb_nombresucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_nombreadmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_nombreproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_compraLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_compraLayout.createSequentialGroup()
                                .addComponent(jl_subtotal)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel14))
                            .addGroup(jPanel_compraLayout.createSequentialGroup()
                                .addComponent(jl_iva)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel15))
                            .addGroup(jPanel_compraLayout.createSequentialGroup()
                                .addComponent(jl_totalcompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_iva, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_subtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jtf_totalcompra))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel_compraLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jb_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jb_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(39, 39, 39))))
        );
        jPanel_compraLayout.setVerticalGroup(
            jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_compraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_idcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_subtotal)
                    .addComponent(jtf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jl_idcompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_fechacompra)
                    .addComponent(jcb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_iva)
                    .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcb_nombresucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_totalcompra)
                        .addComponent(jtf_totalcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(jl_nombresucursal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_compraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nombreadmin)
                            .addComponent(jcb_nombreadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcb_nombreproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nombreproveedor))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_compraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        jPanel_detallecompra.setBackground(new java.awt.Color(153, 153, 153));

        jl_nombreproducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombreproducto.setText("Nombre del producto:");

        jl_precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_precio.setText("Precio:");

        jl_cantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_cantidad.setText("Cantidad:");

        jtf_idcompra_det.setEnabled(false);
        jtf_idcompra_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idcompra_detActionPerformed(evt);
            }
        });

        jtf_precio.setEditable(false);

        jtf_cantidad.setEditable(false);

        jtab_detalle_compra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtab_detalle_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jtab_detalle_compra);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("$");

        jb_agregarproducto.setBackground(new java.awt.Color(153, 153, 153));
        jb_agregarproducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_agregarproducto.setForeground(new java.awt.Color(153, 0, 0));
        jb_agregarproducto.setText("Agregar Producto");
        jb_agregarproducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));

        jb_primero.setBackground(new java.awt.Color(153, 153, 153));
        jb_primero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_primero.setForeground(new java.awt.Color(51, 51, 51));
        jb_primero.setText("|<");
        jb_primero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jb_anterior.setBackground(new java.awt.Color(153, 153, 153));
        jb_anterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_anterior.setForeground(new java.awt.Color(51, 51, 51));
        jb_anterior.setText("<<");
        jb_anterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jb_siguiente.setBackground(new java.awt.Color(153, 153, 153));
        jb_siguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_siguiente.setForeground(new java.awt.Color(51, 51, 51));
        jb_siguiente.setText(">>");
        jb_siguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jb_ultimo.setBackground(new java.awt.Color(153, 153, 153));
        jb_ultimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_ultimo.setForeground(new java.awt.Color(51, 51, 51));
        jb_ultimo.setText(">|");
        jb_ultimo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jl_idcompra_det.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_idcompra_det.setText("ID Compra:");

        jb_fincompra.setBackground(new java.awt.Color(153, 153, 153));
        jb_fincompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_fincompra.setText("Terminar Compra");
        jb_fincompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));

        jb_eliminarproducto.setBackground(new java.awt.Color(153, 153, 153));
        jb_eliminarproducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_eliminarproducto.setForeground(new java.awt.Color(153, 0, 0));
        jb_eliminarproducto.setText("Eliminar Producto");
        jb_eliminarproducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));

        javax.swing.GroupLayout jPanel_detallecompraLayout = new javax.swing.GroupLayout(jPanel_detallecompra);
        jPanel_detallecompra.setLayout(jPanel_detallecompraLayout);
        jPanel_detallecompraLayout.setHorizontalGroup(
            jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                                        .addComponent(jl_cantidad)
                                        .addGap(81, 81, 81))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_detallecompraLayout.createSequentialGroup()
                                        .addComponent(jl_precio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_detallecompraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_idcompra_det)
                                    .addComponent(jl_nombreproducto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_cantidad)
                            .addComponent(jtf_precio)
                            .addComponent(jcb_nombreproducto, 0, 154, Short.MAX_VALUE)
                            .addComponent(jtf_idcompra_det))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_agregarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_eliminarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_detallecompraLayout.createSequentialGroup()
                        .addComponent(jb_fincompra, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jb_primero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jb_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel_detallecompraLayout.setVerticalGroup(
            jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_idcompra_det, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_idcompra_det))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nombreproducto)
                            .addComponent(jcb_nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_precio)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_cantidad)
                            .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_detallecompraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_ultimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_fincompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_primero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_detallecompraLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel_detallecompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_agregarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_eliminarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_detallecompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_detallecompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_nombreproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_nombreproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_nombreproveedorActionPerformed

    private void jtf_idcompra_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idcompra_detActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idcompra_detActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel_compra;
    public javax.swing.JPanel jPanel_detallecompra;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_agregarproducto;
    public javax.swing.JButton jb_anterior;
    public javax.swing.JButton jb_eliminarproducto;
    public javax.swing.JButton jb_fincompra;
    public javax.swing.JButton jb_insertar;
    public javax.swing.JButton jb_modificar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_primero;
    public javax.swing.JButton jb_siguiente;
    public javax.swing.JButton jb_ultimo;
    public javax.swing.JComboBox<String> jcb_dia;
    public javax.swing.JComboBox<String> jcb_mes;
    public javax.swing.JComboBox<String> jcb_nombreadmin;
    public javax.swing.JComboBox<String> jcb_nombreproducto;
    public javax.swing.JComboBox<String> jcb_nombreproveedor;
    public javax.swing.JComboBox<String> jcb_nombresucursal;
    public javax.swing.JLabel jl_cantidad;
    public javax.swing.JLabel jl_fechacompra;
    public javax.swing.JLabel jl_idcompra;
    public javax.swing.JLabel jl_idcompra_det;
    public javax.swing.JLabel jl_iva;
    public javax.swing.JLabel jl_nombreadmin;
    public javax.swing.JLabel jl_nombreproducto;
    public javax.swing.JLabel jl_nombreproveedor;
    public javax.swing.JLabel jl_nombresucursal;
    public javax.swing.JLabel jl_precio;
    public javax.swing.JLabel jl_subtotal;
    public javax.swing.JLabel jl_totalcompra;
    public javax.swing.JTable jtab_detalle_compra;
    public javax.swing.JTextField jtf_anio;
    public javax.swing.JTextField jtf_cantidad;
    public javax.swing.JTextField jtf_idcompra;
    public javax.swing.JTextField jtf_idcompra_det;
    public javax.swing.JTextField jtf_iva;
    public javax.swing.JTextField jtf_precio;
    public javax.swing.JTextField jtf_subtotal;
    public javax.swing.JTextField jtf_totalcompra;
    // End of variables declaration//GEN-END:variables
}
